---
title: "SPARS_B: probability of rating including zero"
author: "Peter Kamerman and Tory Madden"
date: "`r format(Sys.Date(), '%d %b %Y')`"
output: 
  html_document:
    keep_md: true
    theme: yeti
    hightlight: pygments
    toc: true
    toc_depth: 5
    toc_float: true
    code_folding: show
---

```{r setup, include = FALSE}
# Load packages
library(tidyverse)
library(magrittr)
library(boot)

# Set ggplot theme
theme_set(new = theme_bw())

# knitr setup
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.height = 8,
                      fig.width = 8,
                      fig.align = 'center',
                      fig.path = './figures/SPARSB_probability/',
                      cache = TRUE)
```

----

## Question
For each stimulus intenisty, what is the probability that the set of eight repeated stimuli include zero?

To answer this question, we generated 1999 resamples (with replacement) of n = 8 intensity ratings at each stimulus intensity for each study participant. We then counted how many of these resamples included zero. 

The binomial distribution estimates that extreme values for a sequence of eight repeats crossing zero is $x \leq$ 1 or $x \geq$ 7, when the probability of crossing zero for each trial is _p_ = 0.5 (i.e., there is an even chance that a rating will be above or below zero). This assumption does not take into account that as the stimulus intensity becomes more extreme (in either direction) the probability probably of a sequence of ratings inclusing zero probably becomes less. 

----

## Import and inspect data

```{r import}
# Import
data <- read_rds('data/SPARS_B.rds')

# Inspect
glimpse(data)
```

----

## Resample data and calculate simple probability

```{r resample}
# Nest in preparation for resampling by intenisty within each participant
data_boot <- data %>%
    # Select columns
    select(PID, intensity, rating) %>% 
    # Group and nest
    group_by(PID, intensity) %>%
    nest()

# Define a bootstrap function to determine whether the resampled set includes zero
boot_func <- function(d, i) {
    # Generate resample
    data <- d[i, ]
    # Extract rating data form resample
    rating <- data$rating
    # Determine min and max values of the ratings
    min <- min(rating, na.rm = TRUE)
    max <- max(rating, na.rm = TRUE)
    # If the range includes zero, mark as TRUE
    ifelse(min <= 0 & max >= 0,
           yes = TRUE,
           no = FALSE)
}

# Resample
data_boot %<>% 
    mutate(resample = map(.x = data, 
                          # Resample
                          ~ boot(data = .x,
                                 statistic = boot_func,
                                 R = 1999,
                                 stype = 'i') %>% 
                              # Extract resample outputs
                              .$t %>% 
                              as.vector(.) %>% 
                              data.frame(crosses_zero = .) %>% 
                              # Calculate simple probability
                              summarise(cross = sum(crosses_zero),
                                        total = nrow(.),
                                        probability = cross / total)))

# Extract probability
data_boot %<>%
    mutate(probability = map_dbl(.x = resample,
                                 ~ .x$probability))
```

----

## Plot

### Prepare data

```{r plot_data}
plot_data <- data_boot %>% 
    select(PID, intensity, probability)
```

### Heatmap

```{r heatmap}
# Draw heatmap of probabilities across stimulus intensities
ggplot(data = plot_data) +
    aes(x = intensity,
        y = 'ID',
        fill = probability) +
    geom_tile() +
    labs(title = 'Probability of a sequence of eight stimuli including zero',
         subtitle = 'Please note that stimulus intensity range differs between participants',
         x = 'Stimulus intensity (J)') +
    scale_x_continuous(breaks = seq(1, 4.5, by = 0.25),
                       expand = c(0, 0)) +
    scale_y_discrete(expand = c(0, 0)) +
    scale_fill_viridis_c(name = 'Probability',
                         option = 'C') +
    facet_wrap(~ PID,
               ncol = 3,
               scales = 'free_x') +
    theme(axis.title.y = element_blank(),
          axis.text.y = element_blank(),
          panel.grid = element_blank())
```


### Barplot

```{r barplot}
# Draw a barplot of probabilities across stimulus intensities
ggplot(data = plot_data) +
    aes(x = intensity,
        y = probability,
        fill = probability) +
    geom_col() +
    labs(title = 'Probability of a sequence of eight stimuli including zero',
         subtitle = 'Please note that stimulus intensity range differs between participants',
         x = 'Stimulus intensity (J)',
         y = 'Probability') +
    scale_x_continuous(breaks = seq(1, 4.5, by = 0.25),
                       expand = c(0, 0)) +
    scale_y_continuous(limits = c(0, 1),
                       expand = c(0, 0)) +
    scale_fill_viridis_c(name = 'Probability',
                         option = 'C') +
    facet_wrap(~ PID, 
               ncol = 3,
               scales = 'free_x') +
    theme(panel.grid = element_blank())
```

----

## Session information

```{r session_info}
sessionInfo()
```
